### ISSUE TITLE
Rename Custom Key

### ISSUE THREAD

**Issue by davidjung1977** [rubenkaiser/serverless-offline-eventBridge#10]
I like to suggest to rename the custom key name to support serverless.ts TypeScript Files.

TypeScript:

```
    custom: {
        webpack: {
            webpackConfig: './webpack.config.js',
            includeModules: true
        },

        'serverless-offline-aws-eventbridge': {
            port: 4010,
            debug: true,
            account: '',
            convertEntry: false
        },
    },
```

Using camelCase key 'serverlessOfflineAwsEventbridge' "looks" better and the apostrophe could be deleted.

**Comment by rubenkaiser** [comment]
I think it would be best to keep it consistent with a lot of other large plugins (serverless-offline itself included). Do agree that in case of a typescript serverless file it is not the prettiest but that is the case for all the other plugins as well.
