### ISSUE TITLE
Doesn't inspect event.Detail for pattern matching and doesn't support callbacks.

### ISSUE THREAD

**Issue by volpe** [rubenkaiser/serverless-offline-eventBridge#2]
If you set a pattern that involves `detail` in your serverless config, this will not inspect that pattern causing misfires on event handlers.

Also doesn't handle the callback signature that is optional for event bridge callbacks.

I've added these capabilities in this fork (https://github.com/myadbox/serverless-offline-eventBridge), happy to set up a pull request if you're interested.

**Comment by rubenkaiser** [comment]
Always open to improvements. Haven't used the detail property yet, causing the lack of support now. A PR would be great so we can keep improving the plugin

**Comment by rubenkaiser** [comment]
Version 1.2.1 in which this is resolved has just been released
