### ISSUE TITLE
Serverless deploy freezes on moveArtifactsToPackage with 1.6.0

### ISSUE THREAD

**Issue by rcoundon** [rubenkaiser/serverless-offline-eventBridge#33]
After upgrading from 1.5.2 to 1.6.0 the sls deploy freezes and times out in our deployment (seed.run).  
The last two log entries are:

```md
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
```

The serverless packages listed in package.json are:
```
"serverless": "2.43.1",
    "serverless-dependson-plugin": "^1.1.2",
    "serverless-dotenv-plugin": "3.9.0",
    "serverless-dynamodb-local": "0.2.39",
    "serverless-esbuild": "1.12.0",
    "serverless-offline": "7.0.0",
    "serverless-offline-aws-eventbridge": "1.6.0",
    "serverless-offline-dynamodb-streams": "4.2.0",
    "serverless-plugin-epsagon": "1.11.1",
    "serverless-plugin-resource-tagging": "1.1.0",
    "serverless-s3-local": "0.6.17",
    "serverless-stack-output": "0.2.3",
```

After reverting to 1.5.2 the build no longer freezes.

Inside serverless.ts the appropriate configuration is:

```
provider: {
    eventBridge: {
      useCloudFormation: true,
    },
}
...
custom: {
    'serverless-offline-aws-eventbridge': {
      port: 4010,
      debug: true,
      account: '12345678',
    },
}
```

**Comment by rubenkaiser** [comment]
Can you try deploying using the --verbose option? Maybe this will give us a better indication of what is going wrong.

**Comment by damien-thiesson** [comment]
Do you have any specific script configured in your package.json? Also, do you confirm all your serverless packages are listed as devDependencies, and you exclude devDependencies from the artifact build?

**Comment by cristian-pelegrin** [comment]
hi @rcoundon !. any updates with this issue?, did you solve it?, I'm running into the same issue with the same version.
after run the serverless package command the script hang on that part 
![image](https://user-images.githubusercontent.com/12686536/121924639-7a4e7680-cd12-11eb-8551-be8b491b9e07.png)

**Comment by rcoundon** [comment]
Hi - sorry for radio silence, this is happening on the packaging stage and the CI tool we're using (Seed.run) doesn't yet have the option for verbose output for that command but hopefully it's coming soon.

@damien-thiesson In regard to specific scripts, no, it's just a standard `sls deploy --stage someStage`
We don't set `excludeDevDependencies` in serverless.ts and the default is true so my assumption is that the devDependencies are excluded

**Comment by rubenkaiser** [comment]
Just created a test project and at my end it deploys just fine. Can you try to deploy my simple example?

package.json
```
{
	"name": "serverless-offline-eventbridge-deployment-test",
	"version": "1.0.0",
	"description": "",
	"main": "index.js",
	"scripts": {
		"start": "SLS_DEBUG=* sls offline start --log-level info"
	},
	"author": "",
	"license": "ISC",
	"devDependencies": {
		"serverless-offline": "^7.0.0",
		"serverless-offline-aws-eventbridge": "^1.6.0",
		"serverless-webpack": "^5.5.1",
		"webpack": "^5.39.1",
		"webpack-node-externals": "^3.0.0"
	},
	"dependencies": {
		"@babel/core": "^7.8.7",
		"@babel/plugin-transform-runtime": "^7.8.3",
		"@babel/preset-env": "^7.8.7",
		"@babel/runtime": "^7.8.7",
		"aws-sdk": "^2.633.0",
		"babel-loader": "^8.0.6",
		"serverless": "2.47.0"
	}
}
```

serverless.yml
```
service: deploymentTestEventBridge

plugins:
  - serverless-webpack
  - serverless-offline-aws-eventbridge
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    #includeModules: true
  serverless-offline:
    host: 0.0.0.0
  serverless-offline-aws-eventbridge:
    port: 4010
    debug: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

functions:
  publishEvent:
    handler: events.publish
    events:
      - http:
          path: publish
          method: get

  consumeEvent:
    handler: events.consume
    events:
      - eventBridge:
          eventBus: marketingDeploymentTestEventBridge
          pattern:
            source:
              - graph
            detail-type:
              - update
            detail:
              trigger:
                name:
                  - company
                event:
                  data:
                    new:
                      status:
                        - archived
                        - open
```

events.js
```
import AWS from 'aws-sdk';

AWS.config.update({
  apiVersion: '2015-10-07',
  accessKeyId: "YOURKEY",
  secretAccessKey: "YOURSECRET",
  region: "eu-west-1"
});

export const publish = async () => {
  try {
    const eventBridge = new AWS.EventBridge({
      endpoint: 'http://127.0.0.1:4010',
      region: 'eu-west-1'
    });
    const test = await eventBridge.putEvents({
      Entries: [
        {
          EventBusName: 'marketingDeploymentTestEventBridge',
          Source: 'graph',
          DetailType: 'update',
          Detail: JSON.stringify({
            trigger: {
              name: "company",
              event: {
                data: {
                  // test: 'bla',
                  new: {
                    status: 'archived'
                  }
                }
              }

            }

          })
        },
      ]
    }).promise();

  } catch (e) {
    console.error(e);
    return { statusCode: 400, body: 'could not publish' };
  }
  return { statusCode: 200, body: 'published' };
}

export const consume = async (event, context) => {
  console.log("CONSUME 2");
  console.log(event);
  return { statusCode: 200, body: 'consume2' };
}
```

webpack.config.js
```
const slsw = require("serverless-webpack");
const nodeExternals = require("webpack-node-externals");

module.exports = {
  entry: slsw.lib.entries,
  target: "node",
  // Since 'aws-sdk' is not compatible with webpack,
  // we exclude all node dependencies
  externals: [nodeExternals()],
  mode: slsw.lib.webpack.isLocal ? "development" : "production",
  optimization: {
    // We no not want to minimize our code.
    minimize: false
  },
  performance: {
    // Turn off size warnings for entry points
    hints: false
  },
  // Run babel on all .js files and skip those in node_modules
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: "babel-loader",
        include: __dirname,
        exclude: /node_modules/
      }
    ]
  }
};
```

**Comment by kevbaldwyn** [comment]
We're getting the same issue on AWS codebuild with a standard `serverless deploy --stage=blah` when using version `1.6.0`. The deploy happens but the process never exits and the build times out. Downgrading to `1.5.2` fixes the issue.

**Comment by rubenkaiser** [comment]
I've released a beta version that should resolve the issue. The problem was with the imports of 'aedes' and 'net' packages, which initialized immediately. This has been moved to the init function of the plugin.

Try the following version: serverless-offline-aws-eventbridge@1.6.1-beta.2

Let me know if this works for you guys.

**Comment by rcoundon** [comment]
> I've released a beta version that should resolve the issue. The problem was with the imports of 'aedes' and 'net' packages, which initialized immediately. This has been moved to the init function of the plugin.
> 
> Try the following version: serverless-offline-aws-eventbridge@1.6.1-beta.2
> 
> Let me know if this works for you guys.

Thanks - I'll give this a go and report back

**Comment by davidjung1977** [comment]
We had the same issue on circleCi and GithubActions. Last lines of Deployment (Verbose Mode):

Serverless: Stack Output saved to file: .serverless/stack-output/outputs.json
Serverless: Stack Output saved to file: .serverless/stack-output/outputs.yml
Serverless: Removing old service artifacts from S3...

Using the serverless-offline-aws-eventbridge@1.6.1-beta.2 solves the problem.

Unfortunately the dependabot marks the 1.6.0. as stable.

**Comment by rubenkaiser** [comment]
I'll release a new version (1.6.1) as soon as the others also confirm it works

**Comment by rcoundon** [comment]
Hi - just to confirm, it worked for us too

**Comment by rubenkaiser** [comment]
serverless-offline-aws-eventbridge@1.6.1 was just released as the stable version.

**Comment by rcoundon** [comment]
> serverless-offline-aws-eventbridge@1.6.1 was just released as the stable version.

Brilliant - thank you
