### ISSUE TITLE
Request: Update serverless-offline peer dependency

### ISSUE THREAD

**Issue by chrisui** [rubenkaiser/serverless-offline-eventBridge#39]
The latest version is now [v8](https://www.npmjs.com/package/serverless-offline) and npm throws an error because of invalid peer dependency (currently dependent on v6).

**Comment by rubenkaiser** [comment]
serverless-offline-aws-eventbridge@1.6.4 was just released. In this release the peerDependency of serverless offline has been changed to >5 (6 or higher).
