### ISSUE TITLE
Retry attempts break the execution

### ISSUE THREAD

**Issue by cjuega** [rubenkaiser/serverless-offline-eventBridge#43]
It seems this change https://github.com/rubenkaiser/serverless-offline-eventBridge/commit/043cafb05d21ecd9e3f5ab7f15ebc2ead726a265 has broken the retries mechanism.

Now, whenever a lambda throws an error, the event isn't retried and serverless-offline is stopped due to an unhandled error.

**Comment by cjuega** [comment]
I believe changing this https://github.com/rubenkaiser/serverless-offline-eventBridge/blob/master/src/index.js#L253 from 
```js
await this.invokeSubscriber(functionKey, entry, retry + 1);
```

to 

```js
return this.invokeSubscriber(functionKey, entry, retry + 1);
```

should fix the issue. I haven't extensively test it though

**Comment by rubenkaiser** [comment]
Your PR has been merged and I've released a new version with the changes:
serverless-offline-aws-eventbridge@1.6.6
