### ISSUE TITLE
Unclear error message

### ISSUE THREAD

**Issue by prabhatmyadbox** [rubenkaiser/serverless-offline-eventBridge#50]
Hi, I'm getting errors as follows:
`serverless-offline-aws-eventbridge :: error: [object Object] occurred in reportAssetEventBridge on 1/10, will retry`

Is the error message not expected to be an Object?

Thanks!

**Comment by prabhatmyadbox** [comment]
I've made a PR to fix this https://github.com/rubenkaiser/serverless-offline-eventBridge/pull/51
Wud appreciate it if someone can have a look. Thanks!

**Comment by rubenkaiser** [comment]
Your PR has been merged and a new version was released (1.6.7). Supporting attributes that are part of the standard Error prototype is a good thing. In the future we might also add the name property.
