### ISSUE TITLE
Setting up serverless-offline-eventBridge 

### ISSUE THREAD

**Issue by carrickkv2** [rubenkaiser/serverless-offline-eventBridge#61]
Hi. I just wanted to find out some specific information. I'll like to setup serverless-offline-eventBridge with python but I currently can't figure out how to do it. Looking at npm, it says as of version 1.4.0 this plugin also supports non-javascript handlers.

The JS handler in the examples/same-stack-publisher-subscriber includes this specific piece of code, which I've found to be the crucial component I can't replicate in Python. 
```
const eventBridge = new AWS.EventBridge({
      endpoint: "http://127.0.0.1:4080/",
      region: "eu-west-1",
    });
```
Mainly the endpoint. Looking at the AWS SDK documentation I can't find any information about what endpoint does, and so I'm confused. The Python docs also don't mention endpoint like the way it's done in the code above.
Apart from using endpoint, is there any way to tell event bridge how to locate same-stack-publisher-subscriber?

**Comment by carrickkv2** [comment]
Hi. For anyone not seeing it in the docs please go here.
https://stackoverflow.com/questions/66929970/boto3-events-eventbridge-configuration-for-localhost

**Comment by rubenkaiser** [comment]
Hi, good to see you figured it out. I've never seen the stackoverflow question before. Just wondering if you'd be interested in making a PR with a Python example in it? Would be a good addition. Thanks

**Comment by carrickkv2** [comment]
> Hi, good to see you figured it out. I've never seen the stackoverflow question before. Just wondering if you'd be interested in making a PR with a Python example in it? Would be a good addition. Thanks

I'll be fine with doing that. I'll create a PR on Saturday so you can look at it.
Cheers
