### ISSUE TITLE
Response is missing JSON structure

### ISSUE THREAD

**Issue by andriesss** [rubenkaiser/serverless-offline-eventBridge#7]
If you post an event to the event bridge a 200 response is returned, but the response does not contain a valid JSON structure. The response structure is defined as follows according to the AWS docs:

```
{
   "Entries": [ 
      { 
         "ErrorCode": "string",
         "ErrorMessage": "string",
         "EventId": "string"
      }
   ],
   "FailedEntryCount": number
}
```

This causes issues with the PHP SDK, because it tries to de-serialize the response, and expects a JSON object.

**Comment by rubenkaiser** [comment]
I've made some changes to the master branch to fix this because I think the PR you made only fixes it when one event is fired. In my update all events are awaited and a properly filled Entries and FailedEntryCount is returned.
