### ISSUE TITLE
Event Pattern doesn't support array of objects.

### ISSUE THREAD

**Issue by shazi57** [rubenkaiser/serverless-offline-eventBridge#86]
Lambda is not triggered if the event payload contains an array of objects that should match an event pattern like the following:

```
#payload
"services": [
    {
        "name": "order"
    }
]
```
```
#event pattern
services:
  name:
    - order
```

Testing locally with the plugin doesn't subscribe the downstream lambda function to the event, but it works fine when deployed.

**Comment by rion18** [comment]
Any news on my PR @rubenkaiser ?

**Comment by rubenkaiser** [comment]
@rion18 I'll try to check it somewhere this week. If it works properly a new package will be release immediately. Thanks
