### ISSUE TITLE
External Functions are not parsed

### ISSUE THREAD

**Issue by davidjung1977** [rubenkaiser/serverless-offline-eventBridge#9]
If the serverless.yml uses external files for the function declaration the functions are not parsed.

Example:

```
functions:
  - ${file(./application/routesA.yml)}
  - ${file(./application/routesB.yml)}
```

**Comment by rubenkaiser** [comment]
Good catch. The list of subscribers is generated before the list of function files is parsed available to the plugin. I have a fix which I will make available within a couple of days. (Just want to do some more tests).

**Comment by rubenkaiser** [comment]
Just published version 1.3.5 in which I've fixed this issue. Can you check if your setup also works now?

**Comment by davidjung1977** [comment]
Great - try it in the next few hours!

**Comment by davidjung1977** [comment]
Great and fast support! It works as expected.

Thank you.
